#!/bin/bash

set -x
## Mention your mysql root password
mysql_root_password=[your password]

DATE=`date +%F-%H-%M-%S`

docker exec [container_id]  mysqldump -u root -p$mysql_root_password [database_name] > wp-$DATE.sql && echo "wp-$DATE has been created on `date`" >> database_backup.log

